#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

#=================================================================================
# Tiling options
#=================================================================================

# bsp or float (default: float)
yabai -m config layout bsp

# Override default layout for space 4 only
# yabai -m config --space 4 layout float

# New window spawns to the right if vertical split, or bottom if horizontal split
# yabai -m config window_placement second_child

# New window spawns to the left if vertical split, or top if horizontal split
yabai -m config window_placement first_child

#=================================================================================
# Padding and gaps
#=================================================================================

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

# Override gaps for space 2 only
yabai -m config --space 3 window_gap 0

#=================================================================================
# Mouse support
#=================================================================================
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# yabai -m config focus_follows_mouse autoraise

#=================================================================================
# Window modifications
#=================================================================================
# floating windows are always on top (default: off)
yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9
yabai -m config normal_window_opacity 1.0

#=================================================================================
# My modifications
#=================================================================================

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label right
yabai -m space 3 --label left
yabai -m space 5 --label center

# float system preferences. Most of these just diable Yabai form resizing them.
# yabai -m query --windows | jq '.[].app'
yabai -m rule --add app="系統偏好設定" manage=off
yabai -m rule --add app="提醒事項" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="終端機" manage=off
yabai -m rule --add app="Commander One" manage=off
yabai -m rule --add app="VNC Viewer" manage=off
yabai -m rule --add app="螢幕共享" manage=off
yabai -m rule --add app="預覽程式" manage=off
yabai -m rule --add app="時光機" manage=off
yabai -m rule --add app="照片" manage=off
yabai -m rule --add app="Snagit 2023" manage=off
yabai -m rule --add app="LINE" manage=off
yabai -m rule --add app="活動監視器" manage=off
yabai -m rule --add app="iTube Studio" manage=off
yabai -m rule --add app="Microsoft Remote Desktop" manage=off
# yabai -m rule --add app="Finder" manage=off
# yabai -m rule --add app="GitKraken" manage=off
# yabai -m rule --add app="VirtualBox" manage=off
# yabai -m rule --add app="Google Chrome" manage=off
# yabai -m rule --add app="影像擷取" manage=off
# yabai -m rule --add app="行事曆" manage=off
# yabai -m rule --add app="啟動台" manage=off
# yabai -m rule --add app="Antivirus for Mac" manage=off
echo "yabai configuration loaded.."
